name: Build and Publish Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Materials Compendium
        run: |
            python -m pip install .

      - name: Install dependencies
        run: |
          pip install sphinx \
          cloud_sptheme \
          nbsphinx \
          myst-nb \
          sphinx_design \
          sphinx_autodoc_typehints

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Publish documentation to gh-pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git stash 
          git fetch origin gh-pages
          git checkout gh-pages
          cp -r docs/build/html/* .
          git add .
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Publish docs at $timestamp"
          git push origin gh-pages
